"""Render documentation from rule metadata and the schema.

Everything here is derived: the rule catalog, the README rule table, the schema
field reference and the MITRE ATLAS Navigator layer are regenerated from the
rules and the schema, and the test suite fails when a committed copy drifts.
"""

from __future__ import annotations

import json
from collections import defaultdict
from collections.abc import Sequence

from prompthound import fields, taxonomy
from prompthound.rules import Rule
from prompthound.scenarios import Scenario

_REPO = "https://github.com/NotACop38/PromptHound/blob/main"


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def window(seconds: int) -> str:
    """``300`` -> ``"5-minute"``."""
    for unit, size in (("hour", 3600), ("minute", 60)):
        if seconds % size == 0:
            return f"{seconds // size}-{unit}"
    return f"{seconds}-second"


def _anchor(rule: Rule) -> str:
    return rule.stem.replace("_", "-")


def _requirements(rule: Rule) -> str:
    if rule.requires_content:
        return "Raw content"
    if rule.derived_fields:
        return "Content detector"
    return "Metadata only"


def _mapping_labels(rule: Rule) -> list[str]:
    mappings = rule.mappings
    if mappings is None:
        return []
    atlas = taxonomy.atlas()
    return [
        *(taxonomy.OWASP_LLM.label(i) for i in mappings.owasp_llm),
        *(taxonomy.OWASP_AGENTIC.label(i) for i in mappings.owasp_agentic),
        *(f"[{i}]({taxonomy.atlas_url(i)}) {atlas.entries[i]}" for i in mappings.atlas),
        *(
            f"[{i}]({taxonomy.attack_url(i)}) {taxonomy.ATTACK.entries[i]}"
            for i in mappings.attack
            if i[:1] == "T"
        ),
    ]


def readme_rule_table(rules: Sequence[Rule]) -> str:
    """Compact rule table for the README."""
    lines = [
        "| Rule | Level | Logic | Telemetry | OWASP | ATLAS |",
        "|---|---|---|---|---|---|",
    ]
    for rule in sorted(rules, key=lambda r: (r.category, r.title)):
        mappings = rule.mappings
        owasp = ", ".join((mappings.owasp_llm + mappings.owasp_agentic) if mappings else ())
        atlas = ", ".join(mappings.atlas if mappings else ()) or "—"
        logic = "Correlation" if rule.correlation else "Single event"
        lines.append(
            f"| [{_escape(rule.title)}](docs/rules.md#{_anchor(rule)}) | {rule.level} | {logic} "
            f"| {_requirements(rule)} | {owasp} | {atlas} |"
        )
    return "\n".join(lines) + "\n"


def rule_catalog(rules: Sequence[Rule], scenarios: Sequence[Scenario]) -> str:
    """The full rule catalog (``docs/rules.md``)."""
    cases = {s.rule.relpath: s.cases for s in scenarios}
    atlas = taxonomy.atlas()
    by_category: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        by_category[rule.category].append(rule)

    out = [
        "# Rule catalog",
        "",
        "<!-- Generated by scripts/generate.py from the rules and scenarios. Do not edit. -->",
        "",
        f"{len(rules)} rules. Framework versions: {taxonomy.OWASP_LLM.name} "
        f"{taxonomy.OWASP_LLM.version}; {taxonomy.OWASP_AGENTIC.name} "
        f"{taxonomy.OWASP_AGENTIC.version}; {atlas.name} {atlas.version}; "
        f"{taxonomy.ATTACK.name} {taxonomy.ATTACK.version}.",
        "",
        "**Telemetry** states what a rule needs beyond event metadata: *Content detector* "
        "rules read a field that an upstream detector derives from prompts or responses; "
        "*Raw content* rules search the prompt or response text itself. A framework mapping "
        "records which risk a rule relates to; it is not a claim of complete coverage.",
        "",
    ]
    for category in sorted(by_category):
        out += [f"## {category.replace('_', ' ').capitalize()}", ""]
        for rule in sorted(by_category[category], key=lambda r: r.title):
            out += _rule_section(rule, cases.get(rule.relpath, ()))
    return "\n".join(out).rstrip("\n") + "\n"


def _rule_section(rule: Rule, cases: Sequence[object]) -> list[str]:
    lines = [f'<a id="{_anchor(rule)}"></a>', f"### {rule.title}", "", rule.description, ""]
    rows = [
        ("Rule", f"[`rules/{rule.relpath}`]({_REPO}/rules/{rule.relpath}) · `{rule.id}`"),
        ("Level", rule.level),
        ("Status", rule.status),
    ]
    if rule.correlation:
        correlation = rule.correlation
        group = ", ".join(f"`{name}`" for name in correlation.group_by)
        rows.append(
            (
                "Logic",
                f"{correlation.symbol} {correlation.threshold} matching events per {group} "
                f"in a fixed {window(correlation.timespan)} UTC window",
            )
        )
    else:
        rows.append(("Logic", "Single event"))
    rows.append(("Fields", ", ".join(f"`{name}`" for name in rule.fields)))
    rows.append(("Telemetry", _requirements(rule)))
    labels = _mapping_labels(rule)
    if labels:
        rows.append(("Mappings", "<br>".join(labels)))
    query_path = rule.relpath.removesuffix(".yml")
    rows.append(
        (
            "Queries",
            f"[SPL]({_REPO}/siem/splunk/{query_path}.spl) · "
            f"[KQL]({_REPO}/siem/sentinel/{query_path}.kql) · "
            f"[scenarios]({_REPO}/scenarios/{rule.relpath}) ({len(cases)} cases)",
        )
    )
    lines += ["| | |", "|---|---|", *(f"| {k} | {_escape(v)} |" for k, v in rows), ""]
    lines += ["False positives:", "", *(f"- {fp}" for fp in rule.falsepositives), ""]
    return lines


def schema_reference() -> str:
    """Field reference tables for ``docs/schema.md``."""
    titles = {
        "metadata": "Metadata fields",
        "derived": "Derived fields (produced by a content detector)",
        "content": "Content fields",
    }
    out: list[str] = []
    for data_class, title in titles.items():
        out += [
            f"### {title}",
            "",
            "| Field | Type | Origin | SIEM column | Description |",
            "|---|---|---|---|---|",
        ]
        for field in fields.registry().values():
            if field.data_class != data_class:
                continue
            kind = " or ".join(field.types) or "any"
            if field.is_string_array:
                kind = "string array"
            origin = "OpenTelemetry" if field.origin == "otel" else "PromptHound"
            column = f"`{field.column}`"
            if field.splunk_name != field.column:
                column += f" (Splunk `{field.splunk_name}`)"
            out.append(
                f"| `{field.name}` | {kind} | {origin} | {column} | {_escape(field.description)} |"
            )
        out.append("")
    return "\n".join(out)


def atlas_layer(rules: Sequence[Rule]) -> str:
    """A MITRE ATLAS Navigator layer scoring each technique by its number of rules."""
    atlas = taxonomy.atlas()
    covering: dict[str, list[str]] = defaultdict(list)
    for rule in rules:
        for technique in rule.mappings.atlas if rule.mappings else ():
            covering[technique].append(rule.title)
    techniques: list[dict[str, object]] = [
        {
            "techniqueID": technique,
            "score": len(titles),
            "comment": "; ".join(sorted(titles)),
            "enabled": True,
            "showSubtechniques": True,
        }
        for technique, titles in sorted(covering.items())
    ]
    highest = max((len(titles) for titles in covering.values()), default=1)
    layer = {
        "name": "PromptHound rule mappings",
        "versions": {"layer": "4.3", "navigator": "4.6.4"},
        "domain": "atlas-atlas",
        "description": (
            "Number of PromptHound rules mapped to each ATLAS technique. A mapping is not a "
            "measure of detection coverage."
        ),
        "metadata": [{"name": "atlas_data_version", "value": atlas.version}],
        "techniques": techniques,
        "gradient": {
            "colors": ["#dbe9f6", "#1f5f9f"],
            "minValue": 0,
            "maxValue": highest,
        },
        "hideDisabled": False,
    }
    return json.dumps(layer, indent=2) + "\n"


__all__ = ["atlas_layer", "readme_rule_table", "rule_catalog", "schema_reference", "window"]
