"""Convert rules to Splunk SPL and KQL, and render the SIEM deployment files.

Selection rules convert directly through pySigma. For correlation rules, the
Splunk backend emits pySigma's own ``bin``/``stats`` search; the Kusto backend
has no correlation support, so the base detection is converted and the
aggregation is appended here. Both use fixed UTC windows of the rule's
timespan, which is what :mod:`prompthound.correlate` evaluates offline.

Every SPL search starts with a search macro (default ``prompthound_audit``)
that scopes it to the audit-event index and sourcetype.
"""

from __future__ import annotations

import json
import re
from collections.abc import Sequence
from dataclasses import dataclass

from sigma.collection import SigmaCollection
from sigma.rule import SigmaRule

from prompthound import __version__, fields
from prompthound.backends import kusto_backend, splunk_backend
from prompthound.rules import Rule

#: Splunk sourcetype for the normalized audit events.
SPLUNK_SOURCETYPE = "prompthound:audit"

#: Name of the Splunk app directory and its identifier.
SPLUNK_APP = "prompthound"

_MACRO_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_GENERATED = "Generated by PromptHound {version}. Do not edit; regenerate instead."


@dataclass(frozen=True)
class Queries:
    """The SPL and KQL for one rule."""

    rule: Rule
    spl: str
    kql: str


def convert(
    rule: Rule,
    *,
    splunk_macro: str = fields.DEFAULT_SPLUNK_MACRO,
    sentinel_table: str = fields.DEFAULT_SENTINEL_TABLE,
) -> Queries:
    """Convert one rule to SPL and KQL."""
    if not _MACRO_NAME.fullmatch(splunk_macro):
        raise ValueError(f"not a valid Splunk macro name: {splunk_macro!r}")
    return Queries(
        rule=rule,
        spl=_spl(rule, splunk_macro),
        kql=_kql(rule, sentinel_table),
    )


def _fresh(rule: Rule) -> SigmaCollection:
    # pySigma pipelines mutate the rules they process, so every conversion
    # starts from a new parse of the file.
    return SigmaCollection.from_yaml(rule.path.read_text(encoding="utf-8"))


def _single(queries: Sequence[object], rule: Rule, target: str) -> str:
    if len(queries) != 1:
        raise ValueError(f"{rule.relpath}: expected one {target} query, got {len(queries)}")
    return str(queries[0])


def _spl(rule: Rule, macro: str) -> str:
    query = _single(splunk_backend().convert(_fresh(rule)), rule, "SPL")
    lines = [line.rstrip() for line in query.splitlines() if line.strip()]
    lines[0] = f"`{macro}` {lines[0]}"
    return "\n".join(lines)


def _kql(rule: Rule, table: str) -> str:
    backend = kusto_backend(table)
    if rule.correlation is None:
        return _single(backend.convert(_fresh(rule)), rule, "KQL")
    base = next(r for r in _fresh(rule).rules if isinstance(r, SigmaRule))
    standalone = SigmaCollection([SigmaRule.from_dict(base.to_dict())])
    query = _single(backend.convert(standalone), rule, "KQL")
    correlation = rule.correlation
    columns = [fields.get(name).column for name in correlation.group_by]
    lines = [query]
    if columns:
        lines.append("| where " + " and ".join(f"isnotempty({c})" for c in columns))
    span = _span(correlation.timespan)
    lines += [
        f"// Fixed {span} UTC windows: a burst that straddles a window boundary is split.",
        "| summarize event_count = count() by " + ", ".join([*columns, f"bin(timestamp, {span})"]),
        f"| where event_count {correlation.symbol} {correlation.threshold}",
    ]
    return "\n".join(lines)


def _span(seconds: int) -> str:
    for unit, size in (("h", 3600), ("m", 60)):
        if seconds % size == 0:
            return f"{seconds // size}{unit}"
    return f"{seconds}s"


def _conf_value(text: str) -> str:
    """A multi-line value in .conf syntax (backslash line continuation)."""
    return " \\\n".join(text.splitlines())


def _header(comment: str = "#") -> str:
    return f"{comment} {_GENERATED.format(version=__version__)}\n"


def savedsearches_conf(queries: Sequence[Queries]) -> str:
    """``savedsearches.conf`` with one disabled, unscheduled search per rule."""
    stanzas = [
        _header() + "# Searches are unscheduled. See docs/deployment.md before enabling alerts.\n"
    ]
    for item in queries:
        rule = item.rule
        description = f"{rule.description} Level: {rule.level}. Rule ID: {rule.id}."
        stanzas.append(
            f"[PromptHound - {rule.title}]\n"
            f"description = {description}\n"
            f"search = {_conf_value(item.spl)}\n"
            "dispatch.earliest_time = -24h@h\n"
            "dispatch.latest_time = now\n"
            "enableSched = 0\n"
        )
    return "\n".join(stanzas)


def macros_conf(macro: str = fields.DEFAULT_SPLUNK_MACRO, index: str = "prompthound") -> str:
    """``macros.conf`` defining the search macro every PromptHound search starts with."""
    return (
        _header()
        + f"[{macro}]\n"
        + f'definition = index={index} sourcetype="{SPLUNK_SOURCETYPE}"\n'
        + "iseval = 0\n"
        + "description = Scopes PromptHound searches to the normalized audit events. "
        + "Set the index to the one that receives them.\n"
    )


def props_conf() -> str:
    """``props.conf`` for normalized audit events (one JSON object per line)."""
    return (
        _header()
        + f"[{SPLUNK_SOURCETYPE}]\n"
        + "SHOULD_LINEMERGE = false\n"
        + "LINE_BREAKER = ([\\r\\n]+)\n"
        + "# Audit events with prompts can be large; truncating one corrupts its JSON.\n"
        + "TRUNCATE = 0\n"
        + 'TIME_PREFIX = "timestamp":"\n'
        + "TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6N%Z\n"
        + "MAX_TIMESTAMP_LOOKAHEAD = 32\n"
        + "KV_MODE = json\n"
        + "AUTO_KV_JSON = true\n"
    )


def app_conf() -> str:
    return (
        _header()
        + "[install]\nis_configured = false\n\n"
        + "[ui]\nis_visible = false\nlabel = PromptHound\n\n"
        + "[launcher]\nauthor = PromptHound contributors\n"
        + "description = Detections for LLM applications and AI agents.\n"
        + f"version = {__version__}\n\n"
        + f"[package]\nid = {SPLUNK_APP}\ncheck_for_updates = false\n"
    )


def default_meta() -> str:
    return _header() + "[]\naccess = read : [ * ], write : [ admin ]\nexport = system\n"


def sentinel_table(table: str = fields.DEFAULT_SENTINEL_TABLE) -> str:
    """Column definitions for the Log Analytics custom table, as JSON.

    Types use the names of Azure Monitor data collection rule stream
    declarations; ``TimeGenerated`` is required by Log Analytics and should be
    set from ``timestamp`` by the ingestion transformation.
    """
    columns = [{"name": "TimeGenerated", "type": "datetime"}]
    for field in fields.registry().values():
        kind = "boolean" if field.sentinel_type == "bool" else field.sentinel_type
        columns.append({"name": field.column, "type": kind, "description": field.description})
    return json.dumps({"name": table, "columns": columns}, indent=2) + "\n"


__all__ = [
    "SPLUNK_APP",
    "SPLUNK_SOURCETYPE",
    "Queries",
    "app_conf",
    "convert",
    "default_meta",
    "macros_conf",
    "props_conf",
    "savedsearches_conf",
    "sentinel_table",
]
